package com.groupe8.model;
// Generated 4 f�vr. 2023, 22:45:41 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Achat generated by hbm2java
 */
@Entity
@Table(name = "achat", catalog = "bd_groupe8")
public class Achat implements java.io.Serializable {

	private Integer achatId;
	private Gerant gerant;
	private float coutTotalAchat;
	private Date dateAchat;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Achat() {
	}

	public Achat(Gerant gerant, float coutTotalAchat, Date dateAchat) {
		this.gerant = gerant;
		this.coutTotalAchat = coutTotalAchat;
		this.dateAchat = dateAchat;
	}

	public Achat(Gerant gerant, float coutTotalAchat, Date dateAchat, Set<Produit> produits) {
		this.gerant = gerant;
		this.coutTotalAchat = coutTotalAchat;
		this.dateAchat = dateAchat;
		this.produits = produits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACHAT_ID", unique = true, nullable = false)
	public Integer getAchatId() {
		return this.achatId;
	}

	public void setAchatId(Integer achatId) {
		this.achatId = achatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GERANT_ID", nullable = false)
	public Gerant getGerant() {
		return this.gerant;
	}

	public void setGerant(Gerant gerant) {
		this.gerant = gerant;
	}

	@Column(name = "COUT_TOTAL_ACHAT", nullable = false, precision = 8)
	public float getCoutTotalAchat() {
		return this.coutTotalAchat;
	}

	public void setCoutTotalAchat(float coutTotalAchat) {
		this.coutTotalAchat = coutTotalAchat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ACHAT", nullable = false, length = 10)
	public Date getDateAchat() {
		return this.dateAchat;
	}

	public void setDateAchat(Date dateAchat) {
		this.dateAchat = dateAchat;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "achats")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
