package com.groupe8.model;
// Generated 4 f�vr. 2023, 22:45:41 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "bd_groupe8")
public class Client implements java.io.Serializable {

	private Integer clientId;
	private String nomClient;
	private String prenomClient;
	private String contactClient;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Client() {
	}

	public Client(String nomClient, String prenomClient, String contactClient) {
		this.nomClient = nomClient;
		this.prenomClient = prenomClient;
		this.contactClient = contactClient;
	}

	public Client(String nomClient, String prenomClient, String contactClient, Set<Commande> commandes) {
		this.nomClient = nomClient;
		this.prenomClient = prenomClient;
		this.contactClient = contactClient;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CLIENT_ID", unique = true, nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "NOM_CLIENT", nullable = false, length = 20)
	public String getNomClient() {
		return this.nomClient;
	}

	public void setNomClient(String nomClient) {
		this.nomClient = nomClient;
	}

	@Column(name = "PRENOM_CLIENT", nullable = false, length = 30)
	public String getPrenomClient() {
		return this.prenomClient;
	}

	public void setPrenomClient(String prenomClient) {
		this.prenomClient = prenomClient;
	}

	@Column(name = "CONTACT_CLIENT", nullable = false, length = 15)
	public String getContactClient() {
		return this.contactClient;
	}

	public void setContactClient(String contactClient) {
		this.contactClient = contactClient;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
