package com.groupe8.model;
// Generated 31 janv. 2023, 09:27:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gamme generated by hbm2java
 */
@Entity
@Table(name = "gamme", catalog = "bd_groupe8")
public class Gamme implements java.io.Serializable {

	private Integer gammeId;
	private String nom;
	private String teint;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Gamme() {
	}

	public Gamme(String nom, String teint) {
		this.nom = nom;
		this.teint = teint;
	}

	public Gamme(String nom, String teint, Set<Produit> produits) {
		this.nom = nom;
		this.teint = teint;
		this.produits = produits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GAMME_ID", unique = true, nullable = false)
	public Integer getGammeId() {
		return this.gammeId;
	}

	public void setGammeId(Integer gammeId) {
		this.gammeId = gammeId;
	}

	@Column(name = "NOM", nullable = false, length = 25)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "TEINT", nullable = false, length = 20)
	public String getTeint() {
		return this.teint;
	}

	public void setTeint(String teint) {
		this.teint = teint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gamme")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
