package com.groupe8.model;
// Generated 4 f�vr. 2023, 22:45:41 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gerant generated by hbm2java
 */
@Entity
@Table(name = "gerant", catalog = "bd_groupe8")
public class Gerant implements java.io.Serializable {

	private Integer gerantId;
	private String nomGerant;
	private String prenomGerant;
	private String contactGerant;
	private String domicileGerant;
	private Date dateDebut;
	private Date dateFin;
	private String password;
	private String login;
	private Set<Commande> commandes = new HashSet<Commande>(0);
	private Set<Achat> achats = new HashSet<Achat>(0);

	public Gerant() {
	}

	public Gerant(String nomGerant, String prenomGerant, String contactGerant, String domicileGerant, Date dateDebut,
			String password, String login) {
		this.nomGerant = nomGerant;
		this.prenomGerant = prenomGerant;
		this.contactGerant = contactGerant;
		this.domicileGerant = domicileGerant;
		this.dateDebut = dateDebut;
		this.password = password;
		this.login = login;
	}

	public Gerant(String nomGerant, String prenomGerant, String contactGerant, String domicileGerant, Date dateDebut,
			Date dateFin, String password, String login, Set<Commande> commandes, Set<Achat> achats) {
		this.nomGerant = nomGerant;
		this.prenomGerant = prenomGerant;
		this.contactGerant = contactGerant;
		this.domicileGerant = domicileGerant;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.password = password;
		this.login = login;
		this.commandes = commandes;
		this.achats = achats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GERANT_ID", unique = true, nullable = false)
	public Integer getGerantId() {
		return this.gerantId;
	}

	public void setGerantId(Integer gerantId) {
		this.gerantId = gerantId;
	}

	@Column(name = "NOM_GERANT", nullable = false, length = 20)
	public String getNomGerant() {
		return this.nomGerant;
	}

	public void setNomGerant(String nomGerant) {
		this.nomGerant = nomGerant;
	}

	@Column(name = "PRENOM_GERANT", nullable = false, length = 30)
	public String getPrenomGerant() {
		return this.prenomGerant;
	}

	public void setPrenomGerant(String prenomGerant) {
		this.prenomGerant = prenomGerant;
	}

	@Column(name = "CONTACT_GERANT", nullable = false, length = 15)
	public String getContactGerant() {
		return this.contactGerant;
	}

	public void setContactGerant(String contactGerant) {
		this.contactGerant = contactGerant;
	}

	@Column(name = "DOMICILE_GERANT", nullable = false, length = 20)
	public String getDomicileGerant() {
		return this.domicileGerant;
	}

	public void setDomicileGerant(String domicileGerant) {
		this.domicileGerant = domicileGerant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "PASSWORD", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "LOGIN", nullable = false, length = 40)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gerant")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gerant")
	public Set<Achat> getAchats() {
		return this.achats;
	}

	public void setAchats(Set<Achat> achats) {
		this.achats = achats;
	}

}
