package com.groupe8.model;
// Generated 4 f�vr. 2023, 22:45:41 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Livreur generated by hbm2java
 */
@Entity
@Table(name = "livreur", catalog = "bd_groupe8")
public class Livreur implements java.io.Serializable {

	private Integer livreurId;
	private String nomLivreur;
	private String contactLivreur;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Livreur() {
	}

	public Livreur(String nomLivreur, String contactLivreur) {
		this.nomLivreur = nomLivreur;
		this.contactLivreur = contactLivreur;
	}

	public Livreur(String nomLivreur, String contactLivreur, Set<Commande> commandes) {
		this.nomLivreur = nomLivreur;
		this.contactLivreur = contactLivreur;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LIVREUR_ID", unique = true, nullable = false)
	public Integer getLivreurId() {
		return this.livreurId;
	}

	public void setLivreurId(Integer livreurId) {
		this.livreurId = livreurId;
	}

	@Column(name = "NOM_LIVREUR", nullable = false, length = 30)
	public String getNomLivreur() {
		return this.nomLivreur;
	}

	public void setNomLivreur(String nomLivreur) {
		this.nomLivreur = nomLivreur;
	}

	@Column(name = "CONTACT_LIVREUR", nullable = false, length = 15)
	public String getContactLivreur() {
		return this.contactLivreur;
	}

	public void setContactLivreur(String contactLivreur) {
		this.contactLivreur = contactLivreur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livreur")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
