package com.groupe8.model;
// Generated 31 janv. 2023, 09:27:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "bd_groupe8")
public class Produit implements java.io.Serializable {

	private Integer produitId;
	private Gamme gamme;
	private Typeproduit typeproduit;
	private int quantite;
	private String description;
	private Set<Achat> achats = new HashSet<Achat>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Produit() {
	}

	public Produit(Gamme gamme, Typeproduit typeproduit, int quantite) {
		this.gamme = gamme;
		this.typeproduit = typeproduit;
		this.quantite = quantite;
	}

	public Produit(Gamme gamme, Typeproduit typeproduit, int quantite, String description, Set<Achat> achats,
			Set<Commande> commandes) {
		this.gamme = gamme;
		this.typeproduit = typeproduit;
		this.quantite = quantite;
		this.description = description;
		this.achats = achats;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRODUIT_ID", unique = true, nullable = false)
	public Integer getProduitId() {
		return this.produitId;
	}

	public void setProduitId(Integer produitId) {
		this.produitId = produitId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GAMME_ID", nullable = false)
	public Gamme getGamme() {
		return this.gamme;
	}

	public void setGamme(Gamme gamme) {
		this.gamme = gamme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPE_PRODUIT_ID", nullable = false)
	public Typeproduit getTypeproduit() {
		return this.typeproduit;
	}

	public void setTypeproduit(Typeproduit typeproduit) {
		this.typeproduit = typeproduit;
	}

	@Column(name = "QUANTITE", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@Column(name = "DESCRIPTION", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "concerner", catalog = "bd_groupe8", joinColumns = {
			@JoinColumn(name = "PRODUIT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ACHAT_ID", nullable = false, updatable = false) })
	public Set<Achat> getAchats() {
		return this.achats;
	}

	public void setAchats(Set<Achat> achats) {
		this.achats = achats;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "faire_reference", catalog = "bd_groupe8", joinColumns = {
			@JoinColumn(name = "PRODUIT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "COMMANDE_ID", nullable = false, updatable = false) })
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
