package com.groupe8.model;
// Generated 4 f�vr. 2023, 22:45:41 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typeproduit generated by hbm2java
 */
@Entity
@Table(name = "typeproduit", catalog = "bd_groupe8")
public class Typeproduit implements java.io.Serializable {

	private Integer typeProduitId;
	private String intitule;
	private Set<Produit> produits = new HashSet<Produit>(0);

	public Typeproduit() {
	}

	public Typeproduit(String intitule) {
		this.intitule = intitule;
	}

	public Typeproduit(String intitule, Set<Produit> produits) {
		this.intitule = intitule;
		this.produits = produits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TYPE_PRODUIT_ID", unique = true, nullable = false)
	public Integer getTypeProduitId() {
		return this.typeProduitId;
	}

	public void setTypeProduitId(Integer typeProduitId) {
		this.typeProduitId = typeProduitId;
	}

	@Column(name = "INTITULE", nullable = false, length = 30)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeproduit")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

}
